<?php
 $mediaurl = $this->getUrl('pub/media').'homesliderimage/'; 
 $homesliderdata = $block->getHomesliderList();
?>

<div id="demo">
    <div class="container">
      <div class="row">
        <div class="span12">
          <div id="owl-demo" class="owl-carousel">            
            <?php foreach($homesliderdata as $item): 
              $imageurl = $mediaurl.$item['image'];
            ?>             
              <div class="item"><img src="<?php echo $imageurl; ?>" alt="The Last of us"></div>
            <?php endforeach; ?>
            
          </div>

        </div>
      </div>
    </div>
</div>   
<style>
    #owl-demo .item img{
        display: block;
        width: 100%;
        height: auto;
    }
</style>
<script>
	require(['jquery', 'owlCarousel'], function ($) {
        $(document).ready(function() {
		    $("#owl-demo").owlCarousel({

			    navigation : true,
			    slideSpeed : 300,
			    paginationSpeed : 400,
			    singleItem : true

			    // "singleItem:true" is a shortcut for:
			    // items : 1, 
			    // itemsDesktop : false,
			    // itemsDesktopSmall : false,
			    // itemsTablet: false,
			    // itemsMobile : false
		    });
	    });
    });   
</script> 